### ISSUE TITLE
Error running checkout-enroll.py script

### ISSUE THREAD

**Issue by chrismaltais** [jarrettyeo/NTUOSS-SeleniumFacebookAPIforUdemy#1]
## I am unable to use BS4 to scrape the needed DOM selectors

**Note:** I've ran through the guidable tutorial once without issue. Today, I attempted to use the 5 scripts in Part 4 to scrape the latest links from the Facebook page provided. _I did not edit my DB in any way, and am adding on to the same one as before._

I was walking through Part 4.5, and was able to execute (on OSX):
1) `python3 facebook-bitly.py`
2) `python3 bitly-expanded.py`
3) `python3 expanded-udemy.py`

However, when executing `udemy-checkout.py` I get the following output on my console:

```
error, skipping row 620 to next...

error, skipping row 621 to next...

error, skipping row 624 to next...

error, skipping row 648 to next...

error, skipping row 678 to next...

error, skipping row 680 to next...

error, skipping row 686 to next...

error, skipping row 707 to next...

error, skipping row 715 to next...

error, skipping row 734 to next...
```

I tried troubleshooting, and when printing the output of `sample` or `sample.text` on line 26, I get `None`, which after reading through the BS4 docs means the .find() function couldn't find the specified DOM argument.

Below is a screenshot of my DB, I have the Udemy link for each (which works when manually copy pasting into address bar), the issue is just getting the checkout URL.

<img width="1129" alt="screen shot 2017-11-26 at 10 38 04 pm" src="https://user-images.githubusercontent.com/17098959/33240981-875024ac-d2fa-11e7-9537-583f796c6e5e.png">

I'll continue investigating, let me know if you spot an issue!

**Comment by jarrettyeo** [comment]
Hey Chris, thanks for raising this issue. 

**Reason:**
Chances are these courses have been removed or that they were once temporarily free but now are paid (and thus you cannot retrieve the URL or other course information such as name and price). Encountering such errors is normal because I wrote the code to do a catch-all for all exceptions from lines 22 to 93 in ```udemy-checkout.py```. If you could do me a favor, try opening these URLs in your browser and take a look at the course webpage. It will most probably tell you that the course is currently unavailable for enrollment or that it is no longer free.

**Debugging:**
Since any exceptions raised under ```try``` could have triggered the ```except``` portion of the code (line 91 onwards), it would be best to simply comment lines 22 and 91-93 (removing try/except) and of course unindenting lines 23 to 89 once. You will be able to catch the exception this way. Again, as explained, Python will most probably raise an exception that it is unable to retrieve a particular course information when scrapping the Udemy course webpage.

Alternatively, you can always additionally print the traceback in the said ```except``` from line 91 onwards. Replace lines 91 to 93 with the following to view the full traceback more easily:
```
    except:
        traceback.print_stack() # print("error, skipping row", str(udemy_tr.id), "to next...\n")
        pass
```
For the above to work, you will additionally need to add the dependency at the top of your ```udemy-checkout.py``` file by replacing line 1 with:
```import requests, urllib, traceback # , beautifulsoup4```

You can check [this](https://stackoverflow.com/questions/3702675/how-to-print-the-full-traceback-without-halting-the-program) out for more ways of hunting for the traceback.

**Resolving the Issue:**
These exceptions can be safely ignored. It might come across as a huge waste of time reiterating through all these courses when running ```udemy-checkout.py```, but this actually double checks if the course is truly unavailable for enrollment every time you run the code. This can definitely get annoying once your database grows to thousands of records, but it can simply be resolved by inserting a remark (in your db) that this course cannot be enrolled and we want to skip this in the future, and you can do this by updating ```except``` from line 91 onwards:

```
except:
    udemy_tr.status = "udemy-checkout error"
    session.commit()
```

And then you can filter these out when running ```udemy-checkout.py``` by updating line 18 to include this additional filter:

```for udemy_tr in session.query(Course).filter(Course.status == "udemy url found").filter(Course.post_date.isnot("reddit")).filter(Course.status.isnot("udemy-checkout error")):```

Hope this helps. Cheers!
